<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'items search');
?>

<h1><?php echo $translate('Advanced item search'); ?></h1>
<form id="advanced-search" method="get" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
<?php echo $this->partial(
    'common/advanced-search',
    ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']
); ?>
<div id="page-actions">
    <input type="submit" name="submit" class="btn__primary-filled" value="<?php echo $this->escapeHtml($translate('Search')); ?>">
    <input type="reset" name="reset" class="reset-button btn--secondary" value="<?php echo $this->escapeHtml($translate('Reset')); ?>">
</div>
</form>
