<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//use.typekit.net/gny4vcq.css');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();

if ($userBar) {
    $this->htmlElement('body')->appendAttribute('class', 'user-bar');
}

// Get the current URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? "https" : "http";
$host = $_SERVER['HTTP_HOST'];
$requestUri = $_SERVER['REQUEST_URI'];
$currentUrl = $protocol . "://" . $host . $requestUri;

// Extract the last part
$currentPage = basename(parse_url($currentUrl, PHP_URL_PATH));
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $this->partial('common/header', ['userBar' => $userBar, 'site' => $site]); ?>
        <?php echo $this->partial('common/menu-drawer'); ?>

        <?php if ($currentPage === 'home') : ?>
            <?php echo $this->partial('common/banner'); ?>
        <?php endif; ?>

        <div id="main-content" class="<?php echo $currentPage === 'home' ? 'container' : 'medium-container'; ?>" role="main">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->partial('common/footer'); ?>

        <?php
        echo $this->inlineScript()
            ->prependFile($this->assetUrl('js/navigation.js'))
            ->prependFile($this->assetUrl('js/script.js'));
        ?>
    </body>
</html>
